# underwater camera intrinsics for the Barlus UW-S5-3PBX10
image_width: 3072
image_height: 2048
camera_name: barlus
camera_matrix:
  rows: 3
  cols: 3
  data: [2428.10408,    0.     , 1583.53618,
            0.     , 2164.40084,  955.88933,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.309983, 0.137857, -0.003074, -0.001008, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2124.55664,    0.     , 1589.9281 ,    0.     ,
            0.     , 2004.83789,  939.05245,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
